### PR TITLE
Upgraded rancher, rke2 and other packages

### PR DESCRIPTION
**Pull request by AmreeshTyagi**

### CODE REVIEW

**Comment by wenzel-felix** [comment]
@AmreeshTyagi please check out this https://github.com/wenzel-felix/terraform-hcloud-rancher-cloudflare
I'll add your adjustments there and remove the whole example here, cause I don't want to maintain two sources.

Also, if you want you can verify the new version here now. https://github.com/wenzel-felix/terraform-hcloud-rancher-cloudflare/tree/feature/bump_rke2_module_version

**Comment by AmreeshTyagi** [comment]
Thanks @wenzel-felix . I will check new version once I will create new test cluster in few days. 

Just want to know that by default, `test-cluster` was created with rke1 instead of rke2.
Is it a bug or I have to add some new configuration for RKE2?

**Comment by AmreeshTyagi** [comment]
I ran simple example & I see that DNS entries were created on cloudflare. 
I got error of cloudflare_token, so passed that along with zone id. 

is it expected? I see that cloudflare token was used by cert_manager. Not sure if cert manager is needed here or not.

image

**Comment by AmreeshTyagi** [comment]
> I ran simple example & I see that DNS entries were created on cloudflare. I got error of cloudflare_token, so passed that along with zone id.
> 
> is it expected? I see that cloudflare token was used by cert_manager. Not sure if cert manager is needed here or not.
> 
> image

No worry. I handled it as per my own use case.

**Pull request merged**
